### ISSUE TITLE
AttributeError: 'list' object has no attribute 'T'

### ISSUE THREAD

**Issue by wuzuyin** [JOP-Lee/READ#33]
![06343b48ecb389e3f613c51cdb36e62](https://user-images.githubusercontent.com/52769308/225487005-228f2437-3929-4817-8960-6d2b753de9e8.png)

**Comment by Sylvia6** [comment]
Thank you for your support and attention. Are you using customized data? This error seems to be caused by incorrect camera parameters. Where proj_ Matrix is a 4 * 4 matrix projected by OpenGL into ndc space and related to camera internal parameters. In your error report, you explicitly list has no attribute T, which means that the input parameter m is not an np.array and cannot be converted to a transpose matrix.
